name: tg-simplex-bridge
version: 0.1.0

dependencies:
  - base
  - telegram-bot-simple
  - telegram-bot-api
  - text
  - simplex-chat
  - sqlite-simple
  - mtl
  - filepath
  - containers
  - bytestring

#simplex deps
  - directory == 1.3.*
  - async == 2.2.*
  - simple-logger == 0.1.*
  - unliftio == 0.2.*
  - unliftio-core == 0.2.*
  - simplexmq >= 5.0
  - time == 1.12.*
  - stm
  

executables:
  tg-simplex-bridge:
    source-dirs: 
      - apps/bridge
      - src
    main: Main.hs
    
